version: '3'

services:
  mongo_db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes: 
     - mongo_db:/data/db
    logging:
      driver: none


  appnode:
    build: .
    container_name: appnode
    restart: always
    ports:
      - 3000:1234
    environment:
      - MONGODB_URI=mongodb://mongo_db/user_app
    depends_on:
      - mongo_db
    links:
     - mongo_db
    volumes:
      - .:/usr/src/app

volumes:  
  mongo_db: {}
